![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np
import pandas as pd
import matplotlib as plt

# Print the numpy version and the configuration
print(np.__version__)
print(pd.__version__)
print(plt.__version__)

1.19.2
1.1.3
3.3.2


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
print(np.array([0] * 10))
print(len(np.array([0] * 10)))
print(np.zeros(10))
print(len(np.zeros(10)))

[0 0 0 0 0 0 0 0 0 0]
10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


In [3]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
print(np.arange(10, 50))
print(len(np.arange(10, 50)))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
40


In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
# your code goes here
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [8]:
# your code goes here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [10]:
X = np.arange(4, dtype=np.int)
X = np.ones((2,3))
# your code goes here
np.ones(X.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [12]:
# your code goes here
X = np.ones((2,3))
np.zeros_like(X)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [14]:
# your code goes here
np.ones((4,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [17]:
# your code goes here
np.ones_like(X) * 7

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [23]:
# your code goes here
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [28]:
# your code goes here
np.random.randint(10, size = 3)

array([8, 2, 9])

In [29]:
np.random.randint(10, size=3)

array([2, 1, 6])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [34]:
# your code goes here
np.random.randn(3,3,3)

array([[[-0.42535404,  0.52666735,  0.90499343],
        [-0.73160551, -1.07297923,  0.18339941],
        [ 0.78616881, -2.48711574, -1.07256674]],

       [[ 0.50032076,  0.58802039, -0.02480928],
        [-0.40814284, -0.3919647 ,  0.17494542],
        [ 1.8734    , -1.6540318 , -0.12172294]],

       [[-0.85394766,  1.18694317, -0.47689417],
        [ 1.48372822, -1.13687928, -1.48066939],
        [ 0.44191099, -0.29209659,  1.60561924]]])

In [32]:
#np.random.random((3,3,3))
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 1.5060802 , -0.91248635,  0.2163407 ],
        [-0.60245933, -0.37858883,  0.55428861],
        [ 1.0939993 , -1.26745775,  0.39249039]],

       [[-1.3741407 , -0.75327033, -0.98414894],
        [-0.743757  ,  0.49634222, -0.33272905],
        [-0.09748189, -0.02119298, -1.76895835]],

       [[-0.21955578, -0.2225088 , -3.34652172],
        [-0.4854604 , -0.50991824, -0.25008732],
        [ 0.3656846 ,  0.71644636,  1.07458722]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [3]:
range(20)

range(0, 20)

In [7]:
# your code goes here
#[print(x) for x in thislist]
X = [i for i in range(20)]
Y = np.array(X)
print(Y)
print(X)
type(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [9]:
X = [1, 2, 3]
print(X, type(X))
print(X)
Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1, 2, 3]
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [15]:
# your code goes here
X = np.array(X)
print(X, id(X))
Y = X
print(Y, id(Y))






[5 2 3] 2021130351760
[5 2 3] 2021130351760


In [14]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2021130354080
[5 2 3] 2021130351840


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [22]:
# your code goes here
np.array(10)

array(10)

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [26]:
# your code goes here
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [30]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [31]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [34]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [38]:
# your code goes here


In [39]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [40]:
Z.size

100

In [41]:
Z.itemsize

8

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [42]:
# your code goes here
np.arange(10)[0]

0

In [43]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [44]:
# your code goes here
np.arange(100)[-1]


99

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [47]:
# your code goes here
np.arange(100)[:3]
np.arange(100)[0:3]

[0 1 2]
[0 1 2]


In [48]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [49]:
# your code goes here
np.arange(100)[len(np.arange(100)/2)]

IndexError: index 100 is out of bounds for axis 0 with size 100

In [50]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [51]:
# your code goes here
np.arange(100)[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [52]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [63]:
# your code goes here


np.arange(100)[ np.arange( 1,len(np.arange(100) ), 2) ]

np.arange(100)[::2]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [62]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [77]:
# your code goes here
print(np.zeros((3,3))[0,:])
print(np.identity(4)[0,:])
np.arange(100).reshape(10,10)[0]

[0. 0. 0.]
[1. 0. 0. 0.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [79]:
# your code goes here
X[-1]

array([13, 14, 15, 16])

In [80]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [81]:
# your code goes here
X[0,0]

1

In [82]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [83]:
# your code goes here
X[-1,-1]

16

In [84]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [85]:
# your code goes here









In [86]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [87]:
# your code goes here
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [88]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [91]:
# your code goes here
X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [92]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [95]:
# your code goes here
np.array(np.arange(100), np.float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [96]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [97]:
# your code goes here

np.arange(100)[::-1]











array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [112]:
X = [-5, -3, 0, 10, 40]
X = [0, 10, -5, 40, -3]
X[::-1]

[-3, 40, -5, 10, 0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [113]:
# your code goes here
X=np.array(X)
print(X)
print(X.mean())
print(X.std())
X.sort()
print(X)

[ 0 10 -5 40 -3]
8.4
16.620469307453384
[-5 -3  0 10 40]


In [114]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [115]:
# your code goes here

X[4]=1
X







[-5, -3, 0, 10, 1]

In [116]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [119]:
# your code goes here
X = np.arange(100)
X[X==50]=40
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 40,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [121]:
X = np.array([10, 20, 30, 50])
X[X==50]=40
#X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [122]:
# your code goes here
X = np.identity(100)
X[-1] = 1
X

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [123]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [125]:
# your code goes here
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  0]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [127]:
# your code goes here
X += 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 6,  6,  6,  5]])

In [130]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5 # The answer they have.
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [140]:
# your code goes here
X[X<0]
np.random.random(111)
np.random.randn(10, 11)



array([[ 7.59927365e-01,  2.74141329e+00, -8.38363175e-01,
         1.40219808e-02,  4.93232598e-01,  2.23541967e+00,
         2.50231076e-01,  1.02138967e+00, -9.87809460e-01,
         5.82626819e-01, -1.21738813e+00],
       [-8.24626213e-01,  1.65128531e+00,  2.43349792e+00,
         2.08352576e+00,  8.17323824e-01, -8.51154363e-01,
        -2.38601926e+00,  2.00160289e+00,  2.32308488e+00,
        -1.43183766e-02, -8.54734724e-01],
       [-9.51318969e-01, -9.93290440e-01, -1.06179716e+00,
         2.58529996e+00,  1.64498782e+00, -3.64590221e-01,
        -1.60719769e+00,  7.32788480e-01,  6.32926169e-01,
         8.93110993e-01,  1.27660813e+00],
       [ 1.19184449e+00,  3.43012208e-01, -1.14517325e+00,
        -1.29385388e+00,  1.30725832e+00,  1.57183060e+00,
         2.28333730e-01,  2.71526661e-02, -5.29641115e-01,
         6.33990586e-01, -1.26969723e+00],
       [-8.54192704e-01,  6.01836762e-02, -8.04576464e-01,
         2.05458027e-01, -1.53060635e+00, -1.57292293e+00,
  

In [141]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [142]:
# your code goes here


In [143]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [144]:
# your code goes here


In [145]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [146]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[X>X.mean()]

array([ 2,  5,  6, 10])

In [147]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [151]:
# your code goes here
X[(X==2) | (X==10)]

array([ 2, 10])

In [152]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [153]:
# your code goes here


all(X==0)





False

In [160]:
aa = np.zeros(100)
aa
aa.all()
aaa = aa +1
aaa.all()

True

In [161]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [164]:
# your code goes here
print(X.any())
print(any(X==0))
print(X)

True
True
[-1  2  0 -4  5  6  0  0 -9 10]


In [165]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [166]:
# your code goes here


X.sum()




9

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [167]:
# your code goes here
X.mean()

0.9

In [172]:
print(np.mean(range(100)))
print(np.array(range(100)).mean())

49.5
49.5


In [175]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9])

#np.mean(X)
X.mean()

3.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [186]:
# your code goes here
X = X.reshape(3,3)
print(X.mean(axis=0))
print(X.mean(axis=0)) # Column mean
print(X.mean(0)) # Column mean
print(X.mean(axis=1))
print(X)
print(X.sum(0))

[1.66666667 2.33333333 5.        ]
[1.66666667 2.33333333 5.        ]
[1.66666667 2.33333333 5.        ]
[1. 5. 3.]
[[1 2 0]
 [4 5 6]
 [0 0 9]]
[ 5  7 15]


In [187]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [189]:
# your code goes here
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [190]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [191]:
# your code goes here
X.max()

16

In [20]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X = np.arange(10)
#np.max(X)
X.max()

9

In [21]:
x = X[:9]

In [22]:
print(x)
len(x)

[0 1 2 3 4 5 6 7 8]


9

In [23]:
l = np.array(x).reshape(3,3)
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
print(l.mean(axis = 1))
print(l.mean(axis = 0))
print(l.mean())

[1. 4. 7.]
[3. 4. 5.]
4.0


In [32]:
print(l.var())
print(type(l.mean(axis = 1).to_list))

6.666666666666667


AttributeError: 'numpy.ndarray' object has no attribute 'to_list'

In [35]:
type(np.array([1,2,3]).tolist())

list

In [36]:
import numpy as np

def calculate(list):

  try:

    #if len(list) !=9:
    #  print("List must contain nine numbers.")

    #if len(list) == 9:
      l = np.array(list).reshape(3,3)

      dictionary = {
      'mean': [l.mean(axis = 0).tolist(), l.mean(axis = 1).tolist(), l.mean()],
      'variance': [l.var(axis = 0).tolist() , l.var(axis = 1).tolist() , l.var() ],
      'standard deviation': [l.std(axis = 0).tolist() , l.std(axis = 1).tolist() , l.std() ],
      'max': [l.max(axis = 0).tolist() , l.max(axis = 1).tolist() , l.max() ],
      'min': [l.min(axis = 0).tolist() , l.min(axis = 1).tolist() , l.min() ],
      'sum': [l.sum(axis = 0).tolist() , l.sum(axis = 1).tolist() , l.sum() ]
      }

      return(dictionary)

  except ValueError:
    raise ValueError("List must contain nine numbers.")

  

In [40]:
calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [41]:
calculate([9,1,5,3,3,3,2,9,0])

{'mean': [[4.666666666666667, 4.333333333333333, 2.6666666666666665],
  [5.0, 3.0, 3.6666666666666665],
  3.888888888888889],
 'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222],
  [10.666666666666666, 0.0, 14.888888888888891],
  9.209876543209875],
 'standard deviation': [[3.0912061651652345,
   3.39934634239519,
   2.0548046676563256],
  [3.265986323710904, 0.0, 3.8586123009300755],
  3.0347778408328137],
 'max': [[9, 9, 5], [9, 3, 9], 9],
 'min': [[2, 1, 0], [1, 3, 0], 0],
 'sum': [[14, 13, 8], [15, 9, 11], 35]}

In [45]:
print(calculate([2,6,2,8,4,0,1]))
calculate([2,6,2,8,4,0,1,])

ValueError: List must contain nine numbers.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)